version: '3.8'
services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:mysql://db:3306/plataforma_medicos
      USER_MYSQL: root
      PASSWORD_MYSQL: root
      jwt.secret: UYcE9ttVvz6jdba6duWjVFOp9AjguYbBUXQ0iSPddDhcxeXKCDcuxOc9CQuSP4LZ
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plataforma_medicos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
